version: '3.1'
services:
  popcorn:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - pg

  pg:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - popcorn:/var/lib/postgresql/data
volumes:
  popcorn:
    driver: local

      